name: Build and Push Docker image

on:
  push:
    branches:
      - main-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: harbor.bitworm.net
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: harbor.bitworm.net/reservai-prod/app:${{ github.sha }}

    # TODO: Enable this when tests are working 
    # - name: Run Tests
    #   run: |
    #     docker run --rm harbor.bitworm.net/reservai-prod/app:${{ github.sha }} ./run-tests.sh

    # existing steps...

    - name: Checkout GitOps repository
      uses: actions/checkout@v2
      with:
        repository: yashsahota/ReservAI-gitops
        token: ${{ secrets.GH_PAT }} 
        path: ./ReservAI-gitops

    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'reservai/values-prod.yaml'
        propertyPath: 'image.tag'
        value: ${{ github.sha }}
        repository: yashsahota/ReservAI-gitops
        branch: main
        commitChange: true
        message: 'Update Image Version to $${{ github.sha }}'
        token: ${{ secrets.GH_PAT }}
        workDir: ReservAI-gitops
        commitUserEmail: 'actions@reservai.net'


